set number
set relativenumber
set guicursor=i:block
set noerrorbells
set tabstop=4
set hidden
set cursorline
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set linebreak
set noswapfile
set incsearch
set scrolloff=10
set sidescrolloff=10
set showtabline=0
set laststatus=2
set noshowmode
syntax on 
set nocompatible
filetype off
set nohlsearch
set go+=a
set clipboard=unnamedplus
set confirm
